
services:
  whatsapp-tracker:
    build: .
    container_name: whatsapp-tracker
    ports:
      - "5000:5000"
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - FLASK_RUN_HOST=0.0.0.0
      - PLAYWRIGHT_DEFAULT_LAUNCH_OPTIONS=--headless
    volumes:
      - whatsapp_session:/app/whatsapp_session
      - db_data:/app
    restart: unless-stopped
    shm_size: '2gb'

volumes:
  whatsapp_session:
  db_data: